### ISSUE TITLE
Change download links on the SourceMod topic

### ISSUE THREAD

**Issue by Tiagoquix** [Flyflo/SM-Goomba-Stomp#3]
Hello. Might you change the download links on the [SourceMod topic](https://forums.alliedmods.net/showthread.php?t=111893) to always link to the latest version of the files?

For **Goomba Core 2.0.2**, use this: https://github.com/Flyflo/SM-Goomba-Stomp/archive/master.zip
For **Goomba TF2 1.1.1**, **Goomba CS:S 1.0.2**, and **Goomba L4D 1/2 1.0.2**, use this: https://github.com/Flyflo/SM-Goomba-Stomp-Addons/archive/master.zip

Thanks for your attention.

**Comment by Tiagoquix** [comment]
By doing this, you will **always** include the latest changes (translations, for instance).

**Comment by Flyflo** [comment]
Hello,

I'd rather not link directly to master. I made a new release with the updated translations.
